In [1]:
import tensorflow as tf
import numpy as np
print(tf.__version__)#输出版本

2.1.0


In [2]:
print(tf.test.is_gpu_available())#gpu能用不
print(tf.test.is_built_with_cuda())#cuda能用不

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.
True
True


In [3]:

a  =  np.array([[1,2,3],[4,5,6]])
print(a)
my_tensor= tf.constant(a)#将里面的数据 可以是list或array转化为张量
print(my_tensor)
my_variable = tf.Variable(my_tensor) #tf默认占满显存的
# print(my_variable)#转化为变量 ，变量可以完成大部分张量运算但不能reshape
# #a = tf.Variable()

[[1 2 3]
 [4 5 6]]
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int64)


In [4]:
print(my_tensor.shape)

(2, 3)


In [5]:
my_tensor2 = tf.zeros([2,2])#全0张量 老matlab了 注意写成列表形式
print(my_tensor2.shape)
my_tensor3 = tf.ones([2,3])
tf.dtypes.DType(my_tensor3[0,0])

(2, 2)


tf.float32

几个基本的tf操作有相关的去找这些看能不能用就行了
跟tf.keras同级别相关大类操作的综合的那个class
tf.strings 
tf.as_string()把每个输入转化为字符串
tf.string_to_number()
tf.string_split()
等等......
tf.strings的其中一个重要的作用是可以使字符串成为TensorFlow的第一公民，可以直接加入到模型的输入中
详细来说，我们之前在NLP中如果要将字符串进行计算，需要进行下面几步：

首先需要将字符串分词，例如英文常见用空格、标点分词，中文使用分词器或者干脆按字分词
其次需要计算一个词表，能将每个词对应到一个对应的数字上，一般还要加入一些例如[pad]，[unk]等特殊符号
在训练前将训练集的所有字符串经过上面的结果，都转换为数字符号。或者使用generator等技术在训练中流式转换
那么tf.strings的目的，就是我们为什么不能直接将字符串输入，避免上面的几步？这样做有几个好处：

避免了很多多余的代码，比如额外的分词、计算词表等
保证模型的统一性，例如模型本身就包含了分词和符号转换，就可以直接把模型打包、发布（例如用tensorflow hub），这样别人可以不加载或使用任何第三方代码和程序也能直接用你的模型了
模型发布也可以直接用tensorflow serve等完成，避免第三方介入

tf.debugging 调试用
其中tf.Assert
tf.debugging.assert_all_finite判断张量中不包含nan或inf

tf.dtypes 
tf.as_type()类型转换 
例如tf.complex()把两组实数对应组合（实部，虚部）组成复数
tf.dtypes.DType()表示元素张量是什么类型
...

tf.math各种计算
tf.math.abs
tf.math.add
.....

tf.random各种随机

tf.feture_column 将各种类型的原始数据转化为神经网络能处理的数值数据也能进行标准化离散化分箱等
当然还有别的Class看就完了 下面看一下上面介绍的例子

tf.strings操作

In [6]:
print(tf.strings.bytes_split('hello'))#按字符切割
print(tf.strings.split('hello world'))#单词切割（默认空格）注意出来之后都是tensor格式哦
print(tf.strings.split('h/lll/qq',sep='/'))#按sep切割
print(tf.strings.to_hash_bucket(['hello','world'],num_buckets= 10))#hash编码把字符映射为id，bum_buckets hash有多少数字

tf.Tensor([b'h' b'e' b'l' b'l' b'o'], shape=(5,), dtype=string)
tf.Tensor([b'hello' b'world'], shape=(2,), dtype=string)
tf.Tensor([b'h' b'lll' b'qq'], shape=(3,), dtype=string)
tf.Tensor([8 1], shape=(2,), dtype=int64)


tf.random

In [7]:
a = tf.random.uniform(shape=(5,5),minval=0,maxval=10,dtype=tf.int32,seed=233)
a

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[8, 8, 9, 9, 4],
       [7, 2, 7, 1, 6],
       [3, 6, 1, 8, 9],
       [0, 5, 6, 3, 3],
       [3, 0, 1, 9, 4]], dtype=int32)>

tf.debugging

In [8]:
a = tf.random.uniform(shape=(2,2))
tf.debugging.assert_equal(x=a.shape,y=(2,2))#判断两tensor是否相等相等就是true继续执行 不相等报错

In [9]:
#tf.debugging.assert_equal(x=[1,2,3],y=[1,2,4])#报错示范

tf.math

In [10]:
a = tf.constant([[1,2],[3,4]])
b = tf.constant([[1,0],[0,1]])

tf.print(tf.math.add(a,b))#对应加法 tf.print直接printtensor里的数据其他信息shape dtype就不看了
tf.print(tf.math.subtract(a,b))#-
tf.print(tf.math.multiply(a,b))#对应数字相乘不是矩阵乘法
tf.print(tf.math.divide(a,b))#除法

[[2 2]
 [3 5]]
[[0 2]
 [3 3]]
[[1 0]
 [0 4]]
[[1 inf]
 [inf 4]]


tf.dtypes

In [11]:
x = tf.constant([1.8,2.2],dtype=tf.float32)
x1 = tf.dtypes.cast(x,tf.int32)#变成int类型
x1

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

常用层
tf.nn：底层的函数库，其他各种库可以说都是基于这个底层库来进行扩展的。
tf.keras.layers：如果说tf.nn是轮子，那么tf.keras.layers可以说是汽车。tf.keras.layers是基于tf.nn的高度封装。